### ISSUE TITLE
Is this community like JazzBand but for JavaScript?

### ISSUE THREAD

**Issue by jcbhmr** [unjs/.github#2]
Hello! 👋 I was browsing a bunch of JS-amalgamation GitHub orgs, and I have some questions about this organization:
1. Is this _similarish_ to the @jazzband community but for JavaScript?
2. What's the procedure to add a package to this organization?
3. ~~How is this organization governed?~~ Answered via https://github.com/unjs/governance but I think that could be more visible
4. ~~How many members of this organization are there?~~ How many contributors total?
5. What's the criteria for membership? How open is this org to new stuff?
6. How strict are conventions? What are the _crieria_ for a package to be put under the unjs umbrella?

Related to https://github.com/unjs/website/issues/24

**Comment by Barbapapazes** [comment]
Hello!

Thanks a lot for your questions. They will help us to design our new main website. If you have any others, don't hesitate, they're precious to us. 🙏

**Comment by pi0** [comment]
Feel free to ask any more questions via https://github.com/unjs/community 👍🏼
